-- CBC IESTP DRELM v2.3 - Panel de Administración
-- Ejecutar UNA SOLA VEZ en Supabase > SQL Editor.
-- No borra visitas, usuarios ni padrón al instalarse.

-- 1) Asegura que Luis Isidro sea el administrador.
update public.profiles p
set rol='admin', activo=true
from auth.users u
where p.id=u.id and lower(u.email)=lower('lisidro@drelm.gob.pe');

-- 2) Estado ANULADA y trazabilidad.
alter table public.visitas drop constraint if exists visitas_estado_check;
alter table public.visitas add constraint visitas_estado_check check (estado in ('Borrador','Finalizada','Anulada'));
alter table public.visitas add column if not exists anulada_at timestamptz;
alter table public.visitas add column if not exists anulada_by uuid references auth.users(id);
alter table public.visitas add column if not exists anulada_motivo text;

-- 3) Bitácora administrativa.
create table if not exists public.admin_actions (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references auth.users(id),
  accion text not null,
  entidad text,
  entidad_id text,
  detalle text,
  created_at timestamptz not null default now()
);
alter table public.admin_actions enable row level security;
grant select on public.admin_actions to authenticated;
drop policy if exists admin_actions_read on public.admin_actions;
create policy admin_actions_read on public.admin_actions for select to authenticated using (public.is_admin());

-- 4) El especialista solo puede editar mientras la visita esté en borrador.
drop policy if exists visitas_delete on public.visitas;
create policy visitas_delete on public.visitas for delete to authenticated using (public.is_admin());

drop policy if exists visitas_update on public.visitas;
create policy visitas_update on public.visitas for update to authenticated
using ((user_id=(select auth.uid()) and estado='Borrador') or public.is_admin())
with check ((user_id=(select auth.uid())) or public.is_admin());

drop policy if exists evaluaciones_insert on public.evaluaciones;
create policy evaluaciones_insert on public.evaluaciones for insert to authenticated
with check (exists(select 1 from public.visitas v where v.id=visita_id and ((v.user_id=(select auth.uid()) and v.estado='Borrador') or public.is_admin())));
drop policy if exists evaluaciones_update on public.evaluaciones;
create policy evaluaciones_update on public.evaluaciones for update to authenticated
using (exists(select 1 from public.visitas v where v.id=visita_id and ((v.user_id=(select auth.uid()) and v.estado='Borrador') or public.is_admin())))
with check (exists(select 1 from public.visitas v where v.id=visita_id and ((v.user_id=(select auth.uid()) and v.estado='Borrador') or public.is_admin())));
drop policy if exists evaluaciones_delete on public.evaluaciones;
create policy evaluaciones_delete on public.evaluaciones for delete to authenticated
using (exists(select 1 from public.visitas v where v.id=visita_id and public.is_admin()));

-- Medidas correctivas: mismas reglas de inmutabilidad.
drop policy if exists medidas_update on public.medidas_correctivas;
create policy medidas_update on public.medidas_correctivas for update to authenticated
using (exists(select 1 from public.visitas v where v.id=visita_id and ((v.user_id=(select auth.uid()) and v.estado='Borrador') or public.is_admin())))
with check (exists(select 1 from public.visitas v where v.id=visita_id and ((v.user_id=(select auth.uid()) and v.estado='Borrador') or public.is_admin())));
drop policy if exists medidas_delete on public.medidas_correctivas;
create policy medidas_delete on public.medidas_correctivas for delete to authenticated
using (exists(select 1 from public.visitas v where v.id=visita_id and public.is_admin()));

-- 5) Actualización segura del nombre propio.
create or replace function public.update_my_profile_name(p_nombre text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if auth.uid() is null then raise exception 'No autenticado'; end if;
  if length(trim(coalesce(p_nombre,''))) < 2 then raise exception 'Nombre inválido'; end if;
  update public.profiles set nombre=trim(p_nombre) where id=auth.uid();
end; $$;
grant execute on function public.update_my_profile_name(text) to authenticated;

-- 6) Listado administrativo de usuarios, incluyendo correo y último acceso.
create or replace function public.admin_list_users()
returns table(user_id uuid,email text,nombre text,rol text,activo boolean,created_at timestamptz,last_sign_in_at timestamptz)
language plpgsql security definer set search_path=public,auth as $$
begin
  if not public.is_admin() then raise exception 'Acceso denegado'; end if;
  return query
  select u.id,u.email::text,p.nombre,p.rol,p.activo,u.created_at,u.last_sign_in_at
  from auth.users u left join public.profiles p on p.id=u.id
  order by coalesce(p.nombre,u.email::text);
end; $$;
grant execute on function public.admin_list_users() to authenticated;

create or replace function public.admin_set_user_active(p_user_id uuid,p_activo boolean)
returns void language plpgsql security definer set search_path=public as $$
declare v_email text;
begin
  if not public.is_admin() then raise exception 'Acceso denegado'; end if;
  if p_user_id=auth.uid() and p_activo=false then raise exception 'No puedes retirar tu propio acceso'; end if;
  update public.profiles set activo=p_activo where id=p_user_id;
  select email::text into v_email from auth.users where id=p_user_id;
  insert into public.admin_actions(admin_id,accion,entidad,entidad_id,detalle)
  values(auth.uid(),case when p_activo then 'HABILITAR_USUARIO' else 'RETIRAR_USUARIO' end,'USUARIO',p_user_id::text,coalesce(v_email,''));
end; $$;
grant execute on function public.admin_set_user_active(uuid,boolean) to authenticated;

-- 7) Anulación: conserva la ficha y la excluye operativamente como anulada.
create or replace function public.admin_annul_visit(p_visita_id uuid,p_motivo text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'Acceso denegado'; end if;
  if length(trim(coalesce(p_motivo,'')))<5 then raise exception 'Indica el motivo'; end if;
  update public.visitas set estado='Anulada',anulada_at=now(),anulada_by=auth.uid(),anulada_motivo=trim(p_motivo),updated_at=now()
  where id=p_visita_id and estado='Finalizada';
  if not found then raise exception 'La ficha no existe o no está finalizada'; end if;
  insert into public.admin_actions(admin_id,accion,entidad,entidad_id,detalle)
  values(auth.uid(),'ANULAR_FICHA','VISITA',p_visita_id::text,trim(p_motivo));
end; $$;
grant execute on function public.admin_annul_visit(uuid,text) to authenticated;

-- 8) Eliminación definitiva solo para registros de prueba.
create or replace function public.admin_delete_visit(p_visita_id uuid,p_motivo text)
returns void language plpgsql security definer set search_path=public as $$
declare v_desc text;
begin
  if not public.is_admin() then raise exception 'Acceso denegado'; end if;
  select concat(iestp_nombre,' | ',fecha,' | ',supervisor) into v_desc from public.visitas where id=p_visita_id;
  if v_desc is null then raise exception 'Ficha no encontrada'; end if;
  insert into public.admin_actions(admin_id,accion,entidad,entidad_id,detalle)
  values(auth.uid(),'ELIMINAR_FICHA_PRUEBA','VISITA',p_visita_id::text,coalesce(p_motivo,'')||' | '||v_desc);
  delete from public.visitas where id=p_visita_id;
end; $$;
grant execute on function public.admin_delete_visit(uuid,text) to authenticated;

-- 9) Limpieza total de fichas de prueba. Conserva usuarios, padrón y bitácora.
create or replace function public.admin_clear_test_data(p_confirmacion text)
returns void language plpgsql security definer set search_path=public as $$
declare n bigint;
begin
  if not public.is_admin() then raise exception 'Acceso denegado'; end if;
  if p_confirmacion <> 'LIMPIAR PRUEBAS' then raise exception 'Confirmación incorrecta'; end if;
  select count(*) into n from public.visitas;
  insert into public.admin_actions(admin_id,accion,entidad,detalle)
  values(auth.uid(),'LIMPIAR_DATOS_PRUEBA','SISTEMA','Fichas eliminadas: '||n);
  delete from public.visitas;
end; $$;
grant execute on function public.admin_clear_test_data(text) to authenticated;
