-- CBC IESTP DRELM v2.3.1 - ADMINISTRACION (CORREGIDO PARA LA BASE REAL)
-- Base verificada: public.profiles, public.visitas, public.evaluaciones, public.iestp.
-- Ejecutar UNA SOLA VEZ en Supabase > SQL Editor.
-- Es idempotente: puede ejecutarse aunque una parte del script v2.3 anterior haya alcanzado a crearse.
-- NO elimina visitas, evaluaciones, usuarios ni padrón durante la instalación.

-- 0) Función de rol administrador (se asegura que exista).
create or replace function public.is_admin()
returns boolean
language sql stable security definer set search_path=''
as $$
  select exists (
    select 1 from public.profiles p
    where p.id=(select auth.uid()) and lower(coalesce(p.rol,''))='admin' and p.activo=true
  );
$$;
grant execute on function public.is_admin() to authenticated;

-- 1) Luis Isidro = administrador. No modifica a los demás usuarios.
update public.profiles p
set rol='admin', activo=true
from auth.users u
where p.id=u.id and lower(u.email)=lower('lisidro@drelm.gob.pe');

-- 2) Soporte de seguimiento requerido por la app (faltaba en la base verificada).
alter table public.visitas add column if not exists visita_origen_id uuid references public.visitas(id) on delete set null;
alter table public.visitas add column if not exists numero_visita integer;

create table if not exists public.medidas_correctivas (
  id uuid primary key default gen_random_uuid(),
  visita_id uuid not null references public.visitas(id) on delete cascade,
  variable text not null,
  cbc text,
  codigo_indicador text,
  codigo_medida text not null,
  medida text not null,
  responsable text,
  plazo_dias integer,
  fecha_vencimiento date,
  estado text not null default 'Pendiente' check (estado in ('Pendiente','En proceso','Subsanada')),
  seguimiento text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(visita_id,variable,codigo_medida)
);
alter table public.medidas_correctivas enable row level security;
grant select,insert,update,delete on public.medidas_correctivas to authenticated;

drop policy if exists medidas_read on public.medidas_correctivas;
create policy medidas_read on public.medidas_correctivas for select to authenticated
using (exists(select 1 from public.visitas v where v.id=visita_id));
drop policy if exists medidas_insert on public.medidas_correctivas;
create policy medidas_insert on public.medidas_correctivas for insert to authenticated
with check (exists(select 1 from public.visitas v where v.id=visita_id and ((v.user_id=(select auth.uid()) and v.estado='Borrador') or public.is_admin())));
drop policy if exists medidas_update on public.medidas_correctivas;
create policy medidas_update on public.medidas_correctivas for update to authenticated
using (exists(select 1 from public.visitas v where v.id=visita_id and ((v.user_id=(select auth.uid()) and v.estado='Borrador') or public.is_admin())))
with check (exists(select 1 from public.visitas v where v.id=visita_id and ((v.user_id=(select auth.uid()) and v.estado='Borrador') or public.is_admin())));
drop policy if exists medidas_delete on public.medidas_correctivas;
create policy medidas_delete on public.medidas_correctivas for delete to authenticated
using (public.is_admin());

-- 3) Estado ANULADA y trazabilidad administrativa.
alter table public.visitas drop constraint if exists visitas_estado_check;
alter table public.visitas add constraint visitas_estado_check check (estado in ('Borrador','Finalizada','Anulada'));
alter table public.visitas add column if not exists anulada_at timestamptz;
alter table public.visitas add column if not exists anulada_by uuid references auth.users(id);
alter table public.visitas add column if not exists anulada_motivo text;

-- 4) Bitácora administrativa.
create table if not exists public.admin_actions (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references auth.users(id),
  accion text not null,
  entidad text,
  entidad_id text,
  detalle text,
  created_at timestamptz not null default now()
);
alter table public.admin_actions enable row level security;
grant select on public.admin_actions to authenticated;
grant usage,select on all sequences in schema public to authenticated;
drop policy if exists admin_actions_read on public.admin_actions;
create policy admin_actions_read on public.admin_actions for select to authenticated using (public.is_admin());

-- 5) Lectura institucional acumulada; edición solo del borrador propio o por administrador.
drop policy if exists visitas_read on public.visitas;
create policy visitas_read on public.visitas for select to authenticated using (true);
drop policy if exists visitas_delete on public.visitas;
create policy visitas_delete on public.visitas for delete to authenticated using (public.is_admin());
drop policy if exists visitas_update on public.visitas;
create policy visitas_update on public.visitas for update to authenticated
using ((user_id=(select auth.uid()) and estado='Borrador') or public.is_admin())
with check ((user_id=(select auth.uid())) or public.is_admin());

drop policy if exists evaluaciones_read on public.evaluaciones;
create policy evaluaciones_read on public.evaluaciones for select to authenticated
using (exists(select 1 from public.visitas v where v.id=visita_id));
drop policy if exists evaluaciones_insert on public.evaluaciones;
create policy evaluaciones_insert on public.evaluaciones for insert to authenticated
with check (exists(select 1 from public.visitas v where v.id=visita_id and ((v.user_id=(select auth.uid()) and v.estado='Borrador') or public.is_admin())));
drop policy if exists evaluaciones_update on public.evaluaciones;
create policy evaluaciones_update on public.evaluaciones for update to authenticated
using (exists(select 1 from public.visitas v where v.id=visita_id and ((v.user_id=(select auth.uid()) and v.estado='Borrador') or public.is_admin())))
with check (exists(select 1 from public.visitas v where v.id=visita_id and ((v.user_id=(select auth.uid()) and v.estado='Borrador') or public.is_admin())));
drop policy if exists evaluaciones_delete on public.evaluaciones;
create policy evaluaciones_delete on public.evaluaciones for delete to authenticated
using (public.is_admin());

-- 6) El usuario puede actualizar únicamente su nombre desde Mi cuenta.
create or replace function public.update_my_profile_name(p_nombre text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if auth.uid() is null then raise exception 'No autenticado'; end if;
  if length(trim(coalesce(p_nombre,''))) < 2 then raise exception 'Nombre inválido'; end if;
  update public.profiles set nombre=trim(p_nombre) where id=auth.uid();
end; $$;
grant execute on function public.update_my_profile_name(text) to authenticated;

-- 7) Gestión de especialistas desde el panel Administrador.
create or replace function public.admin_list_users()
returns table(user_id uuid,email text,nombre text,rol text,activo boolean,created_at timestamptz,last_sign_in_at timestamptz)
language plpgsql security definer set search_path=public,auth as $$
begin
  if not public.is_admin() then raise exception 'Acceso denegado'; end if;
  return query
  select u.id,u.email::text,p.nombre,p.rol,p.activo,u.created_at,u.last_sign_in_at
  from auth.users u left join public.profiles p on p.id=u.id
  order by coalesce(p.nombre,u.email::text);
end; $$;
grant execute on function public.admin_list_users() to authenticated;

create or replace function public.admin_set_user_active(p_user_id uuid,p_activo boolean)
returns void language plpgsql security definer set search_path=public,auth as $$
declare v_email text;
begin
  if not public.is_admin() then raise exception 'Acceso denegado'; end if;
  if p_user_id=auth.uid() and p_activo=false then raise exception 'No puedes retirar tu propio acceso'; end if;
  update public.profiles set activo=p_activo where id=p_user_id;
  if not found then raise exception 'Perfil no encontrado'; end if;
  select email::text into v_email from auth.users where id=p_user_id;
  insert into public.admin_actions(admin_id,accion,entidad,entidad_id,detalle)
  values(auth.uid(),case when p_activo then 'HABILITAR_USUARIO' else 'RETIRAR_USUARIO' end,'USUARIO',p_user_id::text,coalesce(v_email,''));
end; $$;
grant execute on function public.admin_set_user_active(uuid,boolean) to authenticated;

-- 8) Anular ficha oficial: NO la borra; conserva trazabilidad.
create or replace function public.admin_annul_visit(p_visita_id uuid,p_motivo text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'Acceso denegado'; end if;
  if length(trim(coalesce(p_motivo,'')))<5 then raise exception 'Indica el motivo'; end if;
  update public.visitas
  set estado='Anulada',anulada_at=now(),anulada_by=auth.uid(),anulada_motivo=trim(p_motivo),updated_at=now()
  where id=p_visita_id and estado='Finalizada';
  if not found then raise exception 'La ficha no existe o no está finalizada'; end if;
  insert into public.admin_actions(admin_id,accion,entidad,entidad_id,detalle)
  values(auth.uid(),'ANULAR_FICHA','VISITA',p_visita_id::text,trim(p_motivo));
end; $$;
grant execute on function public.admin_annul_visit(uuid,text) to authenticated;

-- 9) Eliminar definitivamente una ficha de PRUEBA (evaluaciones y medidas caen por CASCADE).
create or replace function public.admin_delete_visit(p_visita_id uuid,p_motivo text)
returns void language plpgsql security definer set search_path=public as $$
declare v_desc text;
begin
  if not public.is_admin() then raise exception 'Acceso denegado'; end if;
  select concat(iestp_nombre,' | ',fecha,' | ',supervisor) into v_desc from public.visitas where id=p_visita_id;
  if v_desc is null then raise exception 'Ficha no encontrada'; end if;
  insert into public.admin_actions(admin_id,accion,entidad,entidad_id,detalle)
  values(auth.uid(),'ELIMINAR_FICHA_PRUEBA','VISITA',p_visita_id::text,coalesce(p_motivo,'')||' | '||v_desc);
  delete from public.visitas where id=p_visita_id;
end; $$;
grant execute on function public.admin_delete_visit(uuid,text) to authenticated;

-- 10) Limpieza total de fichas de prueba. Conserva usuarios, padrón y bitácora.
create or replace function public.admin_clear_test_data(p_confirmacion text)
returns void language plpgsql security definer set search_path=public as $$
declare n bigint;
begin
  if not public.is_admin() then raise exception 'Acceso denegado'; end if;
  if p_confirmacion <> 'LIMPIAR PRUEBAS' then raise exception 'Confirmación incorrecta'; end if;
  select count(*) into n from public.visitas;
  insert into public.admin_actions(admin_id,accion,entidad,detalle)
  values(auth.uid(),'LIMPIAR_DATOS_PRUEBA','SISTEMA','Fichas eliminadas: '||n);
  delete from public.visitas;
end; $$;
grant execute on function public.admin_clear_test_data(text) to authenticated;

-- 11) Resultado de verificación al terminar.
select
  (select count(*) from public.profiles p join auth.users u on u.id=p.id where lower(u.email)=lower('lisidro@drelm.gob.pe') and p.rol='admin' and p.activo=true) as admin_lisidro_ok,
  to_regclass('public.medidas_correctivas') is not null as medidas_correctivas_ok,
  to_regclass('public.admin_actions') is not null as bitacora_admin_ok;
