-- CBC IESTP DRELM v2.4 - Fidelidad al instrumento Word + reapertura + evidencias normalizadas
-- Ejecutar UNA SOLA VEZ después de ACTUALIZACION_V23_ADMIN.sql.
-- No elimina registros existentes.

-- 1. Campos específicos del instrumento para indicadores que además solicitan URL/GPS.
alter table public.evaluaciones add column if not exists dato_url text;
alter table public.evaluaciones add column if not exists dato_gps text;

-- 2. Evidencias como entidad separada, equivalente funcional a EVIDENCE_MEDIA del documento base.
create table if not exists public.evidencias (
  id bigint generated by default as identity primary key,
  visita_id uuid not null references public.visitas(id) on delete cascade,
  evaluacion_id bigint references public.evaluaciones(id) on delete cascade,
  variable text not null,
  nombre_archivo text,
  file_path text not null,
  gps_precision_m numeric,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  unique(visita_id,variable,file_path)
);
alter table public.evidencias enable row level security;
grant select,insert,update,delete on public.evidencias to authenticated;
grant usage,select on sequence public.evidencias_id_seq to authenticated;

drop policy if exists evidencias_read on public.evidencias;
create policy evidencias_read on public.evidencias for select to authenticated
using (exists(select 1 from public.visitas v where v.id=visita_id));
drop policy if exists evidencias_insert on public.evidencias;
create policy evidencias_insert on public.evidencias for insert to authenticated
with check (exists(select 1 from public.visitas v where v.id=visita_id and ((v.user_id=(select auth.uid()) and v.estado='Borrador') or public.is_admin())));
drop policy if exists evidencias_update on public.evidencias;
create policy evidencias_update on public.evidencias for update to authenticated
using (exists(select 1 from public.visitas v where v.id=visita_id and ((v.user_id=(select auth.uid()) and v.estado='Borrador') or public.is_admin())))
with check (exists(select 1 from public.visitas v where v.id=visita_id and ((v.user_id=(select auth.uid()) and v.estado='Borrador') or public.is_admin())));
drop policy if exists evidencias_delete on public.evidencias;
create policy evidencias_delete on public.evidencias for delete to authenticated
using (exists(select 1 from public.visitas v where v.id=visita_id and public.is_admin()));

-- 2.1 Migra a la nueva entidad las evidencias que ya estaban guardadas en evaluaciones.
insert into public.evidencias(visita_id,evaluacion_id,variable,nombre_archivo,file_path,gps_precision_m,created_by)
select e.visita_id,e.id,e.variable,e.evidencia_nombre,e.evidencia_path,v.gps_precision_m,v.user_id
from public.evaluaciones e
join public.visitas v on v.id=e.visita_id
where nullif(e.evidencia_path,'') is not null
on conflict (visita_id,variable,file_path) do nothing;

-- 3. Trazabilidad de reapertura administrativa.
alter table public.visitas add column if not exists reabierta_at timestamptz;
alter table public.visitas add column if not exists reabierta_by uuid references auth.users(id);
alter table public.visitas add column if not exists reabierta_motivo text;

create or replace function public.admin_reopen_visit(p_visita_id uuid,p_motivo text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'Acceso denegado'; end if;
  if length(trim(coalesce(p_motivo,'')))<5 then raise exception 'Indica el motivo de reapertura'; end if;
  update public.visitas
     set estado='Borrador', finished_at=null, reabierta_at=now(), reabierta_by=auth.uid(),
         reabierta_motivo=trim(p_motivo), updated_at=now()
   where id=p_visita_id and estado='Finalizada';
  if not found then raise exception 'La ficha no existe o no está finalizada'; end if;
  insert into public.admin_actions(admin_id,accion,entidad,entidad_id,detalle)
  values(auth.uid(),'REABRIR_FICHA','VISITA',p_visita_id::text,trim(p_motivo));
end; $$;
grant execute on function public.admin_reopen_visit(uuid,text) to authenticated;

-- 4. Comprobación.
select
  to_regclass('public.evidencias') is not null as evidencias_ok,
  exists(select 1 from information_schema.columns where table_schema='public' and table_name='evaluaciones' and column_name='dato_url') as dato_url_ok,
  exists(select 1 from pg_proc where proname='admin_reopen_visit') as reapertura_admin_ok;
