const EMBEDDED = window.PADRON; let PADRON = JSON.parse(localStorage.getItem('cbc_padron') || 'null') || EMBEDDED; let visits = JSON.parse(localStorage.getItem('cbc_visits') || '[]'); let current = null, indIndex = 0, selectedScore = null;
const $ = id => document.getElementById(id); const esc = s => String(s ?? '').replace(/[&<>\"']/g, m => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '\"': '&quot;', "'": '&#39;' }[m]));
const SBC = window.SUPABASE_CONFIG || {}; const backendConfigured = !!(SBC.url && SBC.publishableKey && window.supabase); const sb = backendConfigured ? window.supabase.createClient(SBC.url, SBC.publishableKey) : null; let authUser = null, profile = null;
function backendMsg(t, bad = false) { let e = $('loginMsg'); if (!e) return; e.textContent = t; e.classList.remove('hidden'); e.style.color = bad ? '#9d2525' : '' }
async function login() { if (!backendConfigured) return backendMsg('Falta configurar Supabase. Completa supabase-config.js antes de publicar.', true); let email = $('loginEmail').value.trim(), password = $('loginPassword').value; if (!email || !password) return backendMsg('Ingresa correo y contraseña.', true); $('loginBtn').disabled = true; let { data, error } = await sb.auth.signInWithPassword({ email, password }); $('loginBtn').disabled = false; if (error) return backendMsg('No fue posible iniciar sesión. Verifica tus credenciales.', true); await enterSession(data.user) }
async function enterSession(user) { authUser = user; let { data } = await sb.from('profiles').select('nombre,rol,activo').eq('id', user.id).maybeSingle(); profile = data || { nombre: user.email, rol: 'supervisor', activo: true }; if (profile.activo === false) { await sb.auth.signOut(); return backendMsg('Tu usuario está deshabilitado.', true) } $('userLabel').textContent = (profile.nombre || user.email) + ' · ' + (profile.rol || 'supervisor'); $('logoutBtn').classList.remove('hidden'); document.body.classList.add('authenticated'); $('appNav').classList.remove('hidden'); const isAdmin=(profile.rol||'').toLowerCase()==='admin'; if($('navPadron')) $('navPadron').classList.toggle('hidden',!isAdmin); if($('quickPadron')) $('quickPadron').classList.toggle('hidden',!isAdmin); await syncFromCloud(); show('home') }
async function logout() { if (sb) await sb.auth.signOut(); authUser = null; profile = null; $('logoutBtn').classList.add('hidden'); $('userLabel').textContent = ''; document.body.classList.remove('authenticated'); if($('appNav')) $('appNav').classList.add('hidden'); show('login') }
async function syncFromCloud() { if (!sb || !authUser) return; let { data: rows, error } = await sb.from('visitas').select('*,evaluaciones(*)').order('created_at', { ascending: true }); if (error) { console.warn(error); return } if (rows) { visits = rows.map(r => ({ id: r.id, cloudId: r.id, ownerId: r.user_id, ie: r.ie_snapshot && Object.keys(r.ie_snapshot).length ? r.ie_snapshot : { COD_MOD: r.cod_mod, CODLOCAL: r.cod_local, CEN_EDU: r.iestp_nombre }, meta: { fecha: r.fecha, hora: r.hora || '', supervisor: r.supervisor, tipo: r.tipo || '', modalidad: r.modalidad || '', gps: r.gps || '', obs: r.observacion_general || '' }, answers: Object.fromEntries((r.evaluaciones || []).map(e => [e.variable, { score: e.puntaje, extra: e.dato_complementario || '', obs: e.observacion || '', evidenceName: e.evidencia_nombre || '', evidencePath: e.evidencia_path || '' }])), status: r.estado, finishedAt: r.finished_at || null })); localStorage.setItem('cbc_visits', JSON.stringify(visits)) } }
async function cloudSave(v) { if (!sb || !authUser) return; let old = current; current = v; let c = calc(); current = old; let diag = c.sum >= 162 ? 'SATISFACTORIO / ÓPTIMO' : c.sum >= 126 ? 'ACEPTABLE CON OBSERVACIONES' : 'EN RIESGO / CRÍTICO'; let payload = { user_id: authUser.id, cod_mod: v.ie.COD_MOD, cod_local: v.ie.CODLOCAL || '', iestp_nombre: v.ie.CEN_EDU, ie_snapshot: v.ie, fecha: v.meta.fecha, hora: v.meta.hora || null, supervisor: v.meta.supervisor, tipo: v.meta.tipo, modalidad: v.meta.modalidad, gps: v.meta.gps || null, observacion_general: v.meta.obs || null, estado: v.status, puntaje_total: c.sum, porcentaje_global: c.pct, diagnostico: diag, updated_at: new Date().toISOString(), finished_at: v.finishedAt || null }; let row, error; if (v.cloudId) { ({ data: row, error } = await sb.from('visitas').update(payload).eq('id', v.cloudId).select().single()) } else { payload.legacy_id = v.id; ({ data: row, error } = await sb.from('visitas').insert(payload).select().single()) } if (error) { console.warn('Cloud save', error); return } v.cloudId = row.id; if (v.id !== row.id) { let oldid = v.id; v.id = row.id; let ix = visits.findIndex(x => x.id === oldid); if (ix >= 0) visits[ix] = v } let ev = Object.entries(v.answers).map(([variable, a]) => { let m = MATRIZ.find(x => x.Variable === variable) || {}; return { visita_id: row.id, variable, cbc: m.CBC || '', codigo: m['Código'] || m.Código || '', indicador: m.Indicador || '', puntaje: a.score, dato_complementario: a.extra || null, observacion: a.obs || null, evidencia_nombre: a.evidenceName || null, updated_at: new Date().toISOString() } }); if (ev.length) { let rr = await sb.from('evaluaciones').upsert(ev, { onConflict: 'visita_id,variable' }); if (rr.error) console.warn('Evaluation sync', rr.error) } localStorage.setItem('cbc_visits', JSON.stringify(visits)) }

function show(id) { document.querySelectorAll('.view').forEach(x => x.classList.add('hidden')); $(id).classList.remove('hidden'); if (id === 'home') home(); if (id === 'institutos') renderIE(); if (id === 'historial') renderHistory(); if (id === 'dashboard') renderDash(); scrollTo(0, 0) }
function home() { $('kpiPadron').textContent = PADRON.length; $('padronN').textContent = PADRON.length; $('kpiVisitas').textContent = visits.length; $('kpiFinal').textContent = visits.filter(v => v.status === 'Finalizada').length; let dates = PADRON.map(x => x.FECHA_ACT).filter(Boolean); $('padronDate').textContent = dates.length ? 'Fuente padrón · actualización declarada: ' + dates[0] : '' }
function setupFilters() { let gs = [...new Set(PADRON.map(x => x.D_GESTION).filter(Boolean))].sort(), ds = [...new Set(PADRON.map(x => x.D_DIST).filter(Boolean))].sort(); $('gestion').innerHTML = '<option value="">Todas las gestiones</option>' + gs.map(x => `<option>${esc(x)}</option>`).join(''); $('distrito').innerHTML = '<option value="">Todos los distritos</option>' + ds.map(x => `<option>${esc(x)}</option>`).join('') }
function renderIE() { let q = ($('searchIE')?.value || '').toLowerCase(), g = $('gestion')?.value || '', d = $('distrito')?.value || ''; let a = PADRON.filter(x => (!q || [x.CEN_EDU, x.COD_MOD, x.CODLOCAL].join(' ').toLowerCase().includes(q)) && (!g || x.D_GESTION === g) && (!d || x.D_DIST === d)); $('ieCount').textContent = `${a.length} registro(s) encontrado(s)`; $('ieList').innerHTML = a.slice(0, 100).map(x => `<div class="ieRow"><div><b>${esc(x.CEN_EDU)}</b><div class="meta">CM ${esc(x.COD_MOD)} · CL ${esc(x.CODLOCAL)} · ${esc(x.D_GESTION)} · ${esc(x.D_DIST)}</div><div class="meta">${esc(x.DIR_CEN || 'Dirección no consignada')}</div></div><button onclick="selectIE('${x.COD_MOD.replace(/'/g, '')}','${x.CODLOCAL.replace(/'/g, '')}')">Seleccionar</button></div>`).join('') + (a.length > 100 ? '<div class="note">Se muestran los primeros 100 resultados. Use la búsqueda para precisar.</div>' : '') }
function selectIE(cm, cl) { let ie = PADRON.find(x => x.COD_MOD === cm && x.CODLOCAL === cl); current = { id: 'V' + Date.now(), ie, meta: {}, answers: {}, status: 'Borrador' }; $('selectedIE').innerHTML = ieCard(ie); let now = new Date(); $('fecha').value = now.toISOString().slice(0, 10); $('hora').value = now.toTimeString().slice(0, 5); show('visita') }
function ieCard(x) { return `<b>${esc(x.CEN_EDU)}</b><div class="meta">Código modular ${esc(x.COD_MOD)} · Código local ${esc(x.CODLOCAL)} · ${esc(x.D_GESTION)} · ${esc(x.D_DIST)}</div><div class="meta">${esc(x.DIR_CEN || '')}</div>` }
function getGPS() { if (!navigator.geolocation) return alert('Geolocalización no disponible.'); navigator.geolocation.getCurrentPosition(p => $('gps').value = p.coords.latitude.toFixed(6) + ', ' + p.coords.longitude.toFixed(6), () => alert('No fue posible obtener la ubicación.')) }
function startVisit() { if (!$('supervisor').value.trim()) return alert('Registra el equipo o supervisor.'); current.meta = { fecha: $('fecha').value, hora: $('hora').value, supervisor: $('supervisor').value, tipo: $('tipo').value, modalidad: $('modalidad').value, gps: $('gps').value, obs: $('obsGeneral').value }; renderCBC(); show('cbc') }
function grouped() { let o = {}; MATRIZ.forEach((x, i) => (o[x.CBC] ??= []).push({ ...x, _i: i })); return o }
function renderCBC() { let groups = grouped(); $('cbcInstitute').textContent = current.ie.CEN_EDU; let done = Object.keys(current.answers).length, total = MATRIZ.length; $('progressText').textContent = `${done} de ${total} indicadores registrados`; $('progressBar').style.width = (done / total * 100) + '%'; $('cbcList').innerHTML = Object.entries(groups).map(([cbc, arr], k) => { let n = arr.filter(x => current.answers[x.Variable]).length, p = Math.round(n / arr.length * 100); return `<div class="cbcCard" onclick="openCBC('${cbc}')"><div class="cbcIcon">${k + 1}</div><div><b>${cbc}</b><div class="meta">${arr[0].Indicador} …</div><div class="bar"><i style="width:${p}%"></i></div><div class="meta">${n}/${arr.length} indicadores</div></div><span>›</span></div>` }).join('') + `<button onclick="summary()">Ver resumen →</button>` }
function openCBC(cbc) { let idx = MATRIZ.findIndex(x => x.CBC === cbc && !current.answers[x.Variable]); if (idx < 0) idx = MATRIZ.findIndex(x => x.CBC === cbc); openInd(idx) }
function openInd(i) { indIndex = Math.max(0, Math.min(MATRIZ.length - 1, i)); let x = MATRIZ[indIndex], a = current.answers[x.Variable] || {}; selectedScore = a.score || null; $('indCBC').textContent = x.CBC + ' · ' + x.Código; $('indCounter').textContent = (indIndex + 1) + ' de ' + MATRIZ.length; $('indTitle').textContent = x.Indicador; $('indCriterion').textContent = x['Criterio técnico de verificación']; $('indEvidence').textContent = x['Evidencias exigibles']; $('indType').textContent = x['Tipo de evaluación (fuente)']; $('scoreBtns').innerHTML = [1, 2, 3, 4, 5].map(n => `<button class="${selectedScore === n ? 'active' : ''}" onclick="pickScore(${n})">${n}</button>`).join(''); $('extraValue').value = a.extra || ''; $('indObs').value = a.obs || ''; $('evidence').value = ''; $('evidenceName').textContent = a.evidenceName ? 'Registrado: ' + a.evidenceName : ''; show('indicator') }
function pickScore(n) { selectedScore = n; document.querySelectorAll('#scoreBtns button').forEach((b, i) => b.classList.toggle('active', i + 1 === n)) }
function saveIndicator() { if (!selectedScore) return alert('Selecciona una valoración de 1 a 5.'); let x = MATRIZ[indIndex], old = current.answers[x.Variable] || {}, f = $('evidence').files[0]; current.answers[x.Variable] = { score: selectedScore, extra: $('extraValue').value, obs: $('indObs').value, evidenceName: f ? f.name : old.evidenceName || '' }; saveDraft(true); if (indIndex < MATRIZ.length - 1) openInd(indIndex + 1); else summary() }
function prevInd() { if (indIndex === 0) { renderCBC(); show('cbc') } else openInd(indIndex - 1) }
function saveAndExit() { if (selectedScore) { let x = MATRIZ[indIndex], old = current.answers[x.Variable] || {}, f = $('evidence').files[0]; current.answers[x.Variable] = { score: selectedScore, extra: $('extraValue').value, obs: $('indObs').value, evidenceName: f ? f.name : old.evidenceName || '' }; } saveDraft(true); renderCBC(); show('cbc') }
function saveDraft(silent = false) { if (!current) return; if (current.ownerId && authUser && current.ownerId !== authUser.id && (profile?.rol||'').toLowerCase() !== 'admin') { if(!silent) alert('Esta visita pertenece a otro especialista y está disponible solo para consulta.'); return; } let i = visits.findIndex(v => v.id === current.id); if (i >= 0) visits[i] = current; else visits.push(current); localStorage.setItem('cbc_visits', JSON.stringify(visits)); if (backendConfigured && authUser) cloudSave(current); if (!silent) { renderCBC(); let old = document.title; document.title = '✓ Borrador guardado'; setTimeout(() => document.title = old, 1200) } }
function calc() { let groups = grouped(), res = []; Object.entries(groups).forEach(([cbc, arr]) => { let vals = arr.map(x => current.answers[x.Variable]?.score).filter(Boolean), max = arr.length * 5, sum = vals.reduce((a, b) => a + b, 0); res.push({ cbc, sum, max, pct: Math.round(sum / max * 100), done: vals.length, total: arr.length }) }); let sum = res.reduce((a, b) => a + b.sum, 0), pct = Math.round(sum / 180 * 100); return { res, sum, pct } }
function summary() { let c = calc(); $('summaryIE').innerHTML = ieCard(current.ie); let groups=grouped(); $('summaryCBC').innerHTML = c.res.map((r,idx) => { let arr=groups[r.cbc]||[]; let lead=arr[0]?.Indicador||''; let detail=arr.map(x=>{let a=current.answers[x.Variable]||{}; return `<div class="sumItem"><div><b>${x.Código} · ${x.Indicador}</b><small>${x['Criterio técnico de verificación']||''}</small></div><span class="scorePill ${a.score?'ok':'pending'}">${a.score?('Valoración '+a.score+'/5'):'Sin registrar'}</span>${a.extra?`<div class="sumExtra"><strong>Dato:</strong> ${a.extra}</div>`:''}${a.obs?`<div class="sumExtra"><strong>Observación:</strong> ${a.obs}</div>`:''}</div>`}).join(''); return `<details class="sumRow sumDetail"><summary><div class="sumTitle"><span class="cbcBadge">${idx+1}</span><div><b>${r.cbc} · ${lead}</b><span class="meta">${r.done}/${r.total} indicadores · ${r.pct}%</span></div></div><span class="sumToggle">Ver detalle ▾</span></summary><div class="bar"><i style="width:${r.pct}%"></i></div><div class="sumItems">${detail}</div></details>` }).join(''); $('globalPct').textContent = c.pct + '%'; $('diag').textContent = c.sum >= 162 ? 'SATISFACTORIO / ÓPTIMO' : c.sum >= 126 ? 'ACEPTABLE CON OBSERVACIONES' : 'EN RIESGO / CRÍTICO'; show('summary') }
function finishVisit() { if (current?.ownerId && authUser && current.ownerId !== authUser.id && (profile?.rol||'').toLowerCase() !== 'admin') return alert('Esta visita pertenece a otro especialista y está disponible solo para consulta.'); if (Object.keys(current.answers).length < MATRIZ.length && !confirm('Hay indicadores sin registrar. ¿Finalizar de todos modos?')) return; current.status = 'Finalizada'; current.finishedAt = new Date().toISOString(); saveDraft(true); alert('Visita finalizada y guardada.'); show('historial') }
function renderHistory() { $('historyList').innerHTML = visits.length ? visits.slice().reverse().map(v => { let old = current; current = v; let c = calc(); current = old; return `<div class="historyRow"><div><b>${esc(v.ie.CEN_EDU)}</b><div class="meta">${esc(v.meta.fecha || '')} · ${esc(v.meta.tipo || '')} · ${esc(v.meta.supervisor || '')}</div><div class="meta">${v.status} · ${c.pct}%</div></div><button onclick="loadVisit('${v.id}')">Abrir</button></div>` }).join('') : '<div class="note">Aún no hay visitas guardadas.</div>' }
function loadVisit(id) { current = visits.find(v => v.id === id); if (!current) return; const own=!current.ownerId || !authUser || current.ownerId===authUser.id; const admin=(profile?.rol||'').toLowerCase()==='admin'; if(current.status==='Finalizada' || (!own && !admin)) { summary(); } else { renderCBC(); show('cbc'); } }
function renderDash() { let finals = visits.filter(v => v.status === 'Finalizada'), sums = Array(7).fill(0), counts = Array(7).fill(0); finals.forEach(v => { let old = current; current = v; calc().res.forEach((r, i) => { sums[i] += r.pct; counts[i]++ }); current = old }); $('dashCards').innerHTML = `<article><b>${PADRON.length}</b><span>IESTP padrón</span></article><article><b>${visits.length}</b><span>Visitas</span></article><article><b>${finals.length}</b><span>Finalizadas</span></article><article><b>${new Set(finals.map(v => v.ie.COD_MOD)).size}</b><span>IESTP visitados</span></article>`; $('dashBars').innerHTML = sums.map((s, i) => { let p = counts[i] ? Math.round(s / counts[i]) : 0; return `<div class="dashBar"><b>CBC ${i + 1}</b><div class="bar"><i style="width:${p}%"></i></div><span>${p}%</span></div>` }).join('') }
function exportCurrent() {
  if(!current) return;
  let c=calc(), groups=grouped();
  let diag=c.sum>=162?'SATISFACTORIO / ÓPTIMO':c.sum>=126?'ACEPTABLE CON OBSERVACIONES':'EN RIESGO / CRÍTICO';
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  let rows='';
  Object.entries(groups).forEach(([cbc,arr],gi)=>{arr.forEach((x,i)=>{let a=current.answers[x.Variable]||{}; rows+=`<tr>${i===0?`<td rowspan="${arr.length}"><b>${esc(cbc)}</b><br>${esc(arr[0].Indicador)}</td>`:''}<td>${esc(x.Código)}</td><td>${esc(x.Indicador)}</td><td>${esc(x['Criterio técnico de verificación'])}</td><td>${esc(x['Evidencias exigibles'])}</td><td>${esc(a.score||'')}</td><td>${esc(a.extra||'')}</td><td>${esc(a.obs||'')}</td><td>${esc(a.evidenceName||'')}</td></tr>`})});
  let html=`<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel"><head><meta charset="utf-8"><style>table{border-collapse:collapse;font-family:Calibri}td,th{border:1px solid #9fbad0;padding:6px;vertical-align:top}th{background:#0b67ad;color:white}.title{font-size:18px;font-weight:bold;background:#dcecf8}.sub{font-weight:bold;background:#edf5fb}</style></head><body><table><tr><td colspan="9" class="title">DRELM - Monitoreo de Condiciones Básicas de Calidad - IESTP</td></tr><tr><td class="sub">Institución</td><td colspan="3">${esc(current.ie.CEN_EDU)}</td><td class="sub">Código modular</td><td>${esc(current.ie.COD_MOD)}</td><td class="sub">Código local</td><td colspan="2">${esc(current.ie.CODLOCAL)}</td></tr><tr><td class="sub">Fecha</td><td>${esc(current.meta.fecha)}</td><td class="sub">Supervisor</td><td colspan="2">${esc(current.meta.supervisor)}</td><td class="sub">Índice global</td><td>${c.pct}%</td><td class="sub">Clasificación</td><td>${esc(diag)}</td></tr><tr><th>CBC / referencia</th><th>Código</th><th>Indicador</th><th>Criterio técnico de verificación</th><th>Evidencias exigibles</th><th>Valoración</th><th>Dato complementario</th><th>Observación</th><th>Evidencia registrada</th></tr>${rows}</table></body></html>`;
  let blob=new Blob(['\ufeff',html],{type:'application/vnd.ms-excel'}),a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`Visita_CBC_${current.ie.COD_MOD}_${current.meta.fecha||''}.xls`; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),1000);
}
function parseCSV(t) { let rows = [], row = [], cell = '', q = false; for (let i = 0; i < t.length; i++) { let c = t[i], n = t[i + 1]; if (c === '"') { if (q && n === '"') { cell += '"'; i++ } else q = !q } else if (c === ',' && !q) { row.push(cell); cell = '' } else if ((c === '\n' || c === '\r') && !q) { if (c === '\r' && n === '\n') i++; row.push(cell); if (row.some(x => x !== '')) rows.push(row); row = []; cell = '' } else cell += c } row.push(cell); if (row.some(x => x !== '')) rows.push(row); return rows }
function importCSV(f) { if (!f) return; let r = new FileReader(); r.onload = () => { let rows = parseCSV(r.result), h = rows.shift().map(x => x.trim().replace(/^\uFEFF/, '')); if (!h.includes('COD_MOD') || !h.includes('CEN_EDU')) return alert('El CSV debe conservar al menos los encabezados COD_MOD y CEN_EDU.'); let arr = rows.map(a => Object.fromEntries(h.map((k, i) => [k, a[i] ?? '']))).filter(x => x.COD_MOD && x.CEN_EDU); arr.forEach(x => { x.COD_MOD = String(x.COD_MOD).padStart(7, '0'); x.CODLOCAL = String(x.CODLOCAL || '').padStart(6, '0') }); PADRON = arr; localStorage.setItem('cbc_padron', JSON.stringify(PADRON)); setupFilters(); home(); alert(`Padrón actualizado: ${arr.length} registros.`) }; r.readAsText(f, 'utf-8') }
function resetPadron() { if (confirm('¿Restaurar el padrón incorporado en esta versión?')) { PADRON = EMBEDDED; localStorage.removeItem('cbc_padron'); setupFilters(); home(); alert('Padrón restaurado.') } }
async function boot() { setupFilters(); home(); $('backendState').textContent = backendConfigured ? 'Conexión Supabase configurada' : 'Modo configuración: falta Project URL y Publishable key'; if (backendConfigured) { let { data } = await sb.auth.getSession(); if (data.session?.user) return enterSession(data.session.user) } show('login') } boot(); if ('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(() => { });
