-- CBC IESTP DRELM - esquema inicial Supabase
-- Ejecutar en Supabase > SQL Editor.
-- Después cree los usuarios en Authentication > Users.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text not null default '',
  rol text not null default 'supervisor' check (rol in ('admin','supervisor','consulta')),
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.iestp (
  id bigint generated by default as identity primary key,
  cod_mod text not null,
  cod_local text not null default '',
  nombre text not null,
  gestion text,
  distrito text,
  direccion text,
  datos jsonb not null default '{}'::jsonb,
  activo boolean not null default true,
  periodo_padron integer,
  updated_at timestamptz not null default now(),
  unique(cod_mod,cod_local)
);

create table if not exists public.visitas (
  id uuid primary key default gen_random_uuid(),
  legacy_id text,
  user_id uuid not null references auth.users(id),
  iestp_id bigint references public.iestp(id),
  cod_mod text not null,
  cod_local text not null default '',
  iestp_nombre text not null,
  ie_snapshot jsonb not null default '{}'::jsonb,
  fecha date not null,
  hora time,
  supervisor text not null,
  tipo text,
  modalidad text,
  gps text,
  observacion_general text,
  estado text not null default 'Borrador' check (estado in ('Borrador','Finalizada')),
  puntaje_total integer not null default 0 check (puntaje_total between 0 and 180),
  porcentaje_global numeric(5,2) not null default 0,
  diagnostico text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  finished_at timestamptz
);

create table if not exists public.evaluaciones (
  id bigint generated by default as identity primary key,
  visita_id uuid not null references public.visitas(id) on delete cascade,
  variable text not null,
  cbc text not null,
  codigo text,
  indicador text,
  puntaje smallint not null check (puntaje between 1 and 5),
  dato_complementario text,
  observacion text,
  evidencia_nombre text,
  evidencia_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(visita_id,variable)
);

create index if not exists visitas_user_id_idx on public.visitas(user_id);
create index if not exists visitas_cod_mod_idx on public.visitas(cod_mod);
create index if not exists evaluaciones_visita_idx on public.evaluaciones(visita_id);

-- Crear perfil automáticamente cuando se crea un usuario.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id,nombre,rol)
  values (new.id, coalesce(new.raw_user_meta_data->>'nombre', split_part(coalesce(new.email,''),'@',1)), 'supervisor')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Seguridad RLS
alter table public.profiles enable row level security;
alter table public.iestp enable row level security;
alter table public.visitas enable row level security;
alter table public.evaluaciones enable row level security;

revoke all on public.profiles from anon;
revoke all on public.iestp from anon;
revoke all on public.visitas from anon;
revoke all on public.evaluaciones from anon;

grant select on public.profiles to authenticated;
grant select on public.iestp to authenticated;
grant select,insert,update,delete on public.visitas to authenticated;
grant select,insert,update,delete on public.evaluaciones to authenticated;
grant usage,select on all sequences in schema public to authenticated;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid()) and p.rol = 'admin' and p.activo
  );
$$;

grant execute on function public.is_admin() to authenticated;

drop policy if exists profiles_read_self_or_admin on public.profiles;
create policy profiles_read_self_or_admin on public.profiles for select to authenticated
using (id = (select auth.uid()) or public.is_admin());

drop policy if exists iestp_read_authenticated on public.iestp;
create policy iestp_read_authenticated on public.iestp for select to authenticated using (true);

drop policy if exists visitas_read on public.visitas;
create policy visitas_read on public.visitas for select to authenticated
using (user_id = (select auth.uid()) or public.is_admin());

drop policy if exists visitas_insert on public.visitas;
create policy visitas_insert on public.visitas for insert to authenticated
with check (user_id = (select auth.uid()));

drop policy if exists visitas_update on public.visitas;
create policy visitas_update on public.visitas for update to authenticated
using (user_id = (select auth.uid()) or public.is_admin())
with check (user_id = (select auth.uid()) or public.is_admin());

drop policy if exists visitas_delete on public.visitas;
create policy visitas_delete on public.visitas for delete to authenticated
using (user_id = (select auth.uid()) or public.is_admin());

drop policy if exists evaluaciones_read on public.evaluaciones;
create policy evaluaciones_read on public.evaluaciones for select to authenticated
using (exists(select 1 from public.visitas v where v.id=visita_id and (v.user_id=(select auth.uid()) or public.is_admin())));

drop policy if exists evaluaciones_insert on public.evaluaciones;
create policy evaluaciones_insert on public.evaluaciones for insert to authenticated
with check (exists(select 1 from public.visitas v where v.id=visita_id and v.user_id=(select auth.uid())));

drop policy if exists evaluaciones_update on public.evaluaciones;
create policy evaluaciones_update on public.evaluaciones for update to authenticated
using (exists(select 1 from public.visitas v where v.id=visita_id and (v.user_id=(select auth.uid()) or public.is_admin())))
with check (exists(select 1 from public.visitas v where v.id=visita_id and (v.user_id=(select auth.uid()) or public.is_admin())));

drop policy if exists evaluaciones_delete on public.evaluaciones;
create policy evaluaciones_delete on public.evaluaciones for delete to authenticated
using (exists(select 1 from public.visitas v where v.id=visita_id and (v.user_id=(select auth.uid()) or public.is_admin())));

-- Bucket privado para evidencias.
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('cbc-evidencias','cbc-evidencias',false,10485760,array['image/jpeg','image/png','image/webp','application/pdf'])
on conflict (id) do nothing;

drop policy if exists cbc_evidencias_insert_own on storage.objects;
create policy cbc_evidencias_insert_own on storage.objects for insert to authenticated
with check (bucket_id='cbc-evidencias' and (storage.foldername(name))[1]=(select auth.uid())::text);

drop policy if exists cbc_evidencias_read_own_or_admin on storage.objects;
create policy cbc_evidencias_read_own_or_admin on storage.objects for select to authenticated
using (bucket_id='cbc-evidencias' and (owner_id=(select auth.uid())::text or public.is_admin()));

drop policy if exists cbc_evidencias_update_own on storage.objects;
create policy cbc_evidencias_update_own on storage.objects for update to authenticated
using (bucket_id='cbc-evidencias' and owner_id=(select auth.uid())::text)
with check (bucket_id='cbc-evidencias' and owner_id=(select auth.uid())::text);

drop policy if exists cbc_evidencias_delete_own_or_admin on storage.objects;
create policy cbc_evidencias_delete_own_or_admin on storage.objects for delete to authenticated
using (bucket_id='cbc-evidencias' and (owner_id=(select auth.uid())::text or public.is_admin()));

-- Para convertir un usuario en administrador después de crearlo:
-- update public.profiles set rol='admin', nombre='NOMBRE' where id='UUID-DEL-USUARIO';
